name: Compile and Release LaTeX PDF

on:
  push:
    branches:
      - main  # Trigger on pushes to main
    paths:
      - 'paper/**'  # Only trigger when files in 'paper/' are changed
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Allow write access to repository contents

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install LaTeX (BasicTeX)
      run: |
        sudo apt-get update
        sudo apt install biber latexmk texlive-plain-generic texlive-latex-base texlive-luatex lmodern \
          fonts-lmodern texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra \
          texlive-bibtex-extra texlive-science texlive-lang-english texlive-lang-portuguese

    - name: Compile LaTeX to PDF
      working-directory: ./paper
      run: latexmk -pdf tese.tex

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v3
      with:
        name: tese-pdf
        path: paper/tese.pdf

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: tese-pdf
        path: .

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "latest"  # Use "latest" to indicate the current release
        files: tese.pdf  # Specify the correct path for the downloaded PDF
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
