name: Matrix Inversion tests

on:
  push:
    branches:
      - main  # Trigger on pushes to main
    paths:
      - 'code/classes/**'  # Only trigger when files in 'code/' are changed
  workflow_dispatch:  # Allows manual triggering

jobs:
  test-matrix-inversion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y make
          
      - name: Compile
        run: |
          cd code
          make test_matrix_inverse
          echo "Done"
