name: CI

on: [push, pull_request]

jobs:
  matrix-inversion-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y make
          
      - name: Compile
        run: |
          cd code/tests/matrix-inverse
          echo "Compiling..."
          make
          echo "Compiled."

      - name: Run
        run: |
          echo "Running..."
          cd code/tests/matrix-inverse
          make run
          echo "Completed."

      - name: Compare
        run: |
          echo "Comparing..."
          cd code/tests/matrix-inverse
          make compare
          echo "Success."
